<?php

namespace App\Http\Requests\Admin;

use Illuminate\Foundation\Http\FormRequest;

class UpdateLandingPageRequest extends FormRequest
{
    public function authorize(): bool
    {
        return $this->user()?->is_admin === true;
    }

    /**
     * @return array<string, mixed>
     */
    public function rules(): array
    {
        return [
            'content.seo.title' => ['required', 'string', 'max:255'],
            'content.seo.description' => ['required', 'string', 'max:500'],
            'content.nav.cta_label' => ['required', 'string', 'max:100'],
            'content.hero.eyebrow' => ['required', 'string', 'max:100'],
            'content.hero.headline_lines' => ['required', 'array', 'min:1', 'max:4'],
            'content.hero.headline_lines.*' => ['required', 'string', 'max:100'],
            'content.hero.headline_emphasis' => ['required', 'string', 'max:100'],
            'content.hero.description' => ['required', 'string', 'max:1000'],
            'content.hero.stats' => ['required', 'array', 'min:1', 'max:6'],
            'content.hero.stats.*.value' => ['required', 'string', 'max:50'],
            'content.hero.stats.*.label' => ['required', 'string', 'max:150'],
            'content.hero.cta_primary' => ['required', 'string', 'max:100'],
            'content.hero.cta_secondary' => ['required', 'string', 'max:100'],
            'content.ticker.enabled' => ['required', 'boolean'],
            'content.ticker.items' => ['required', 'array', 'min:1', 'max:20'],
            'content.ticker.items.*' => ['required', 'string', 'max:150'],
            'content.philosophy.enabled' => ['required', 'boolean'],
            'content.philosophy.eyebrow' => ['required', 'string', 'max:100'],
            'content.philosophy.headline_lines' => ['required', 'array', 'min:1', 'max:4'],
            'content.philosophy.headline_lines.*' => ['required', 'string', 'max:100'],
            'content.philosophy.headline_emphasis' => ['required', 'string', 'max:100'],
            'content.philosophy.paragraphs' => ['required', 'array', 'min:1', 'max:4'],
            'content.philosophy.paragraphs.*' => ['required', 'string', 'max:1000'],
            'content.philosophy.pillars' => ['required', 'array', 'min:1', 'max:6'],
            'content.philosophy.pillars.*.number' => ['required', 'string', 'max:10'],
            'content.philosophy.pillars.*.title' => ['required', 'string', 'max:150'],
            'content.philosophy.pillars.*.description' => ['required', 'string', 'max:500'],
            'content.services.enabled' => ['required', 'boolean'],
            'content.services.eyebrow' => ['required', 'string', 'max:100'],
            'content.services.headline_lines' => ['required', 'array', 'min:1', 'max:4'],
            'content.services.headline_lines.*' => ['required', 'string', 'max:100'],
            'content.services.headline_emphasis' => ['required', 'string', 'max:100'],
            'content.services.description' => ['required', 'string', 'max:1000'],
            'content.services.items' => ['required', 'array', 'min:1', 'max:6'],
            'content.services.items.*.number' => ['required', 'string', 'max:20'],
            'content.services.items.*.title' => ['required', 'string', 'max:150'],
            'content.services.items.*.description' => ['required', 'string', 'max:1000'],
            'content.services.items.*.features' => ['required', 'array', 'min:1', 'max:10'],
            'content.services.items.*.features.*' => ['required', 'string', 'max:200'],
            'content.services.items.*.cta_label' => ['required', 'string', 'max:100'],
            'content.process.enabled' => ['required', 'boolean'],
            'content.process.eyebrow' => ['required', 'string', 'max:100'],
            'content.process.headline' => ['required', 'string', 'max:200'],
            'content.process.headline_emphasis' => ['required', 'string', 'max:100'],
            'content.process.description' => ['required', 'string', 'max:500'],
            'content.process.steps' => ['required', 'array', 'min:1', 'max:6'],
            'content.process.steps.*.number' => ['required', 'string', 'max:10'],
            'content.process.steps.*.title' => ['required', 'string', 'max:150'],
            'content.process.steps.*.description' => ['required', 'string', 'max:500'],
            'content.manifesto.enabled' => ['required', 'boolean'],
            'content.manifesto.quote' => ['required', 'string', 'max:500'],
            'content.manifesto.quote_emphasis' => ['required', 'string', 'max:200'],
            'content.manifesto.attribution' => ['required', 'string', 'max:150'],
            'content.why.enabled' => ['required', 'boolean'],
            'content.why.eyebrow' => ['required', 'string', 'max:100'],
            'content.why.headline_lines' => ['required', 'array', 'min:1', 'max:4'],
            'content.why.headline_lines.*' => ['required', 'string', 'max:100'],
            'content.why.headline_emphasis' => ['required', 'string', 'max:100'],
            'content.why.description' => ['required', 'string', 'max:1000'],
            'content.why.cta_label' => ['required', 'string', 'max:100'],
            'content.why.cards' => ['required', 'array', 'min:1', 'max:8'],
            'content.why.cards.*.title' => ['required', 'string', 'max:150'],
            'content.why.cards.*.description' => ['required', 'string', 'max:500'],
            'content.industries.enabled' => ['required', 'boolean'],
            'content.industries.eyebrow' => ['required', 'string', 'max:100'],
            'content.industries.headline_lines' => ['required', 'array', 'min:1', 'max:4'],
            'content.industries.headline_lines.*' => ['required', 'string', 'max:100'],
            'content.industries.headline_emphasis' => ['required', 'string', 'max:100'],
            'content.industries.items' => ['required', 'array', 'min:1', 'max:20'],
            'content.industries.items.*' => ['required', 'string', 'max:150'],
            'content.cta_strip.enabled' => ['required', 'boolean'],
            'content.cta_strip.headline' => ['required', 'string', 'max:500'],
            'content.cta_strip.description' => ['required', 'string', 'max:1000'],
            'content.cta_strip.button_label' => ['required', 'string', 'max:100'],
            'content.blog.enabled' => ['required', 'boolean'],
            'content.blog.eyebrow' => ['required', 'string', 'max:100'],
            'content.blog.headline' => ['required', 'string', 'max:500'],
            'content.blog.headline_emphasis' => ['required', 'string', 'max:200'],
            'content.blog.cta' => ['required', 'string', 'max:100'],
            'content.blog.empty_message' => ['required', 'string', 'max:500'],
            'content.community.enabled' => ['required', 'boolean'],
            'content.community.eyebrow' => ['required', 'string', 'max:100'],
            'content.community.headline' => ['required', 'string', 'max:500'],
            'content.community.description' => ['required', 'string', 'max:1000'],
            'content.community.cta_label' => ['required', 'string', 'max:100'],
            'content.contact.enabled' => ['required', 'boolean'],
            'content.contact.eyebrow' => ['required', 'string', 'max:100'],
            'content.contact.headline' => ['required', 'string', 'max:500'],
            'content.contact.description' => ['required', 'string', 'max:1000'],
            'content.contact.submit_label' => ['required', 'string', 'max:100'],
            'content.footer.brand_description' => ['required', 'string', 'max:1000'],
            'content.footer.copyright' => ['required', 'string', 'max:200'],
            'content.footer.tagline' => ['required', 'string', 'max:200'],
            'content.footer.service_links' => ['required', 'array', 'min:1', 'max:10'],
            'content.footer.service_links.*.label' => ['required', 'string', 'max:100'],
            'content.footer.service_links.*.href' => ['required', 'string', 'max:255'],
            'content.footer.company_links' => ['required', 'array', 'min:1', 'max:10'],
            'content.footer.company_links.*.label' => ['required', 'string', 'max:100'],
            'content.footer.company_links.*.href' => ['required', 'string', 'max:255'],
            'content.footer.connect_links' => ['required', 'array', 'min:1', 'max:10'],
            'content.footer.connect_links.*.label' => ['required', 'string', 'max:100'],
            'content.footer.connect_links.*.href' => ['required', 'string', 'max:255'],
        ];
    }
}
